name: Daily Financial Data Update

on:
  schedule:
    # Every hour (55 min)
    - cron: '55 * * * *'
  workflow_dispatch:

jobs:
  update-data:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Create credentials file
      env:
        GOOGLE_SHEETS_CREDENTIALS: ${{ secrets.GOOGLE_SHEETS_CREDENTIALS }}
      run: |
        import os
        with open("credentials.json", "w") as f:
            f.write(os.environ['GOOGLE_SHEETS_CREDENTIALS'])
      shell: python

    - name: Run Pipeline
      env:
        SPREADSHEET_ID: ${{ secrets.SPREADSHEET_ID }}
        GOOGLE_SHEETS_CREDENTIALS_PATH: credentials.json
      run: |
        python src/main.py

    - name: Remove credentials file
      if: always()
      run: rm credentials.json
